# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

copyright: (C) 2016 - Michael Seidel
navbar-title: Michael in Neuseeland
header-image: /images/header.png
header-image-height: 100px
header-image-height-small: 50px
baseurl: "" # the subpath of your site, e.g. /blog
title: Michael in Neuseeland
description: > # this means to ignore newlines until "baseurl:"
  Michael in Neuseeland
url: "http://michael-in-neuseeland.de" # the base hostname & protocol for your site, e.g. http://example.com
rss: /feed.xml
permalink: pretty

piwikurl: piwik.seidel-michael.de
piwikid: 2

impressum:
  mail: info@michael-in-neuseeland.de
  url: michael-in-neuseeland.de
  phone: '+4971536086817'
  surname: Michael
  lastname: Seidel
  street: Grundstr. 6
  city: 73262 Reichenbach / Fils
  country: Deutschland


contact:
  php: /php/contact.php
  from: no-reply@michael-in-neuseeland.de 
  to: newsletter@michael-in-neuseeland.de 
  missing: /contact/missing/
  error: /contact/error/
  success: /contact/success/
  subject: "Kontaktforumlar: michael-in-neuseeland.de"
  privacypolicy: /privacypolicy/
  translation:
    label-mail: E-Mail Addresse
    placeholder-mail: E-Mail Addresse eingeben
    label-name: Name
    placeholder-name: Name eingeben
    label-message: Nachricht
    placeholder-message: Nachricht eingeben
    send: Senden
    privacypolicy: zur Datenschutzerklärung


translation:
  read-more: Weiterlesen


picture:
  source: "gallery/"
  output: "gallery"
  markup: "picture"
  presets:
    post-thumbnail:
      ppi: [1]
      attr:
        class: "img-responsive img-thumbnail"
        itemprop: "image"
      source_default: 
        width: "500"
    default:
      ppi: [1]
      attr:
        class: "img-responsive img-thumbnail"
        itemprop: "image"
      source_default: 
        width: "960"


gallerytag:
    magick_lib: mini               # choose this if you use mini_magick
    source_dir: gallery
    destination_dir: gallery/thumbs
    thumb_width: 230
    thumb_height: 153
    columns: 99                     # set to 0 and a <ul> list will be generated
    custom_attribute_name: data-lightbox
    baseurl: 

collections:
  php:
    output: true

# Build settings
markdown: kramdown
theme: minima
gems:
exclude:
  - Gemfile
  - Gemfile.lock
